import { z } from "zod";
import { idSchema } from "./ids.js";

export const eventTypeSchema = z.enum([
  "source.uploaded",
  "source.parse.started",
  "source.parse.completed",
  "source.chunk.started",
  "source.chunk.completed",
  "source.enrichment.started",
  "source.enrichment.completed",
  "source.index.started",
  "source.index.completed",
  "source.tutoring_ready",
  "source.ingestion.ready",
  "source.ingestion.failed",
  "ingestion.job.queued",
  "ingestion.job.started",
  "ingestion.job.completed",
  "ingestion.job.failed",
  "ingestion.job.dead_lettered",
  "wiki.claim.proposed",
  "wiki.claim.admitted",
  "wiki.claim.promoted",
  "wiki.claim.contradicted",
  "wiki.claim.superseded",
  "wiki.page.compiled",
  "wiki.page.updated",
  "wiki.page.invalidated",
  "wiki.lint.completed",
  "curriculum.bootstrap.started",
  "curriculum.bootstrap.completed",
  "curriculum.generated",
  "curriculum.updated",
  "student_profile.updated",
  "objective.created",
  "objective.updated",
  "objective.completed",
  "study_plan.seeded",
  "study_plan.updated",
  "graph.node.created",
  "graph.edge.created",
  "graph.projection.updated",
  "graph.neo4j_projection.updated",
  "graph.neo4j_projection.failed",
  "whiteboard.layout.updated",
  "artifact.created",
  "artifact.proposed",
  "artifact.approved",
  "artifact.rejected",
  "artifact.updated",
  "artifact.ready",
  "artifact.failed",
  "quiz.attempt.recorded",
  "agent.run.started",
  "agent.tool.started",
  "agent.tool.completed",
  "agent.tool.failed",
  "agent.compaction.started",
  "agent.compaction.completed",
  "agent.run.completed",
  "agent.run.failed",
  "tutor.message.delta",
  "tutor.message.completed",
  "tutor.checkpoint.requested",
  "tutor.checkpoint.answered",
  "learning.mastery.updated",
  "learning.weak_concept.added",
  "learning.review.scheduled",
  "session.started",
  "session.focus.updated",
  "session.crystallization.started",
  "session.crystallization.completed",
  "session.completed",
]);

export const eventEnvelopeSchema = z.object({
  id: idSchema,
  notebookId: idSchema,
  sessionId: idSchema.optional(),
  runId: idSchema.optional(),
  eventType: eventTypeSchema,
  sequenceNo: z.number().int().nonnegative(),
  createdAt: z.string().datetime(),
  payload: z.record(z.string(), z.unknown()),
});

export const runtimeStreamChunkKindSchema = z.enum([
  "run-start",
  "message-delta",
  "message-complete",
  "tool-start",
  "tool-complete",
  "tool-error",
  "compaction-start",
  "compaction-complete",
  "run-complete",
  "run-error",
]);

export const runtimeStreamChunkSchema = z.object({
  kind: runtimeStreamChunkKindSchema,
  eventType: eventEnvelopeSchema.shape.eventType,
  notebookId: idSchema,
  sessionId: idSchema.optional(),
  runId: idSchema.optional(),
  sequenceNo: z.number().int().nonnegative(),
  createdAt: z.string().datetime(),
  payload: z.record(z.string(), z.unknown()),
});

export type EventType = z.infer<typeof eventTypeSchema>;
export type EventEnvelope = z.infer<typeof eventEnvelopeSchema>;
export type RuntimeStreamChunkKind = z.infer<typeof runtimeStreamChunkKindSchema>;
export type RuntimeStreamChunk = z.infer<typeof runtimeStreamChunkSchema>;
