/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LearnerRouteImport } from './routes/_learner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnerAppIndexRouteImport } from './routes/_learner/app/index'
import { Route as LearnerNotebooksNotebookIdRouteImport } from './routes/_learner/notebooks/$notebookId'
import { Route as LearnerAppSupportRouteImport } from './routes/_learner/app/support'
import { Route as LearnerAppCreditsRouteImport } from './routes/_learner/app/credits'
import { Route as LearnerAppConsentRouteImport } from './routes/_learner/app/consent'
import { Route as LearnerAppAccessCodeRouteImport } from './routes/_learner/app/access-code'
import { Route as LearnerAppTemplatesIndexRouteImport } from './routes/_learner/app/templates/index'
import { Route as LearnerAppNotebooksIndexRouteImport } from './routes/_learner/app/notebooks/index'
import { Route as LearnerAppWorkspacesNewRouteImport } from './routes/_learner/app/workspaces/new'
import { Route as LearnerAppTemplatesTemplateIdRouteImport } from './routes/_learner/app/templates/$templateId'
import { Route as LearnerAppAccountTabRouteImport } from './routes/_learner/app/account.$tab'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoute = LearnerRouteImport.update({
  id: '/_learner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerAppIndexRoute = LearnerAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerNotebooksNotebookIdRoute =
  LearnerNotebooksNotebookIdRouteImport.update({
    id: '/notebooks/$notebookId',
    path: '/notebooks/$notebookId',
    getParentRoute: () => LearnerRoute,
  } as any)
const LearnerAppSupportRoute = LearnerAppSupportRouteImport.update({
  id: '/app/support',
  path: '/app/support',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppCreditsRoute = LearnerAppCreditsRouteImport.update({
  id: '/app/credits',
  path: '/app/credits',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppConsentRoute = LearnerAppConsentRouteImport.update({
  id: '/app/consent',
  path: '/app/consent',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppAccessCodeRoute = LearnerAppAccessCodeRouteImport.update({
  id: '/app/access-code',
  path: '/app/access-code',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppTemplatesIndexRoute =
  LearnerAppTemplatesIndexRouteImport.update({
    id: '/app/templates/',
    path: '/app/templates/',
    getParentRoute: () => LearnerRoute,
  } as any)
const LearnerAppNotebooksIndexRoute =
  LearnerAppNotebooksIndexRouteImport.update({
    id: '/app/notebooks/',
    path: '/app/notebooks/',
    getParentRoute: () => LearnerRoute,
  } as any)
const LearnerAppWorkspacesNewRoute = LearnerAppWorkspacesNewRouteImport.update({
  id: '/app/workspaces/new',
  path: '/app/workspaces/new',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppTemplatesTemplateIdRoute =
  LearnerAppTemplatesTemplateIdRouteImport.update({
    id: '/app/templates/$templateId',
    path: '/app/templates/$templateId',
    getParentRoute: () => LearnerRoute,
  } as any)
const LearnerAppAccountTabRoute = LearnerAppAccountTabRouteImport.update({
  id: '/app/account/$tab',
  path: '/app/account/$tab',
  getParentRoute: () => LearnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/access-code': typeof LearnerAppAccessCodeRoute
  '/app/consent': typeof LearnerAppConsentRoute
  '/app/credits': typeof LearnerAppCreditsRoute
  '/app/support': typeof LearnerAppSupportRoute
  '/notebooks/$notebookId': typeof LearnerNotebooksNotebookIdRoute
  '/app/': typeof LearnerAppIndexRoute
  '/app/account/$tab': typeof LearnerAppAccountTabRoute
  '/app/templates/$templateId': typeof LearnerAppTemplatesTemplateIdRoute
  '/app/workspaces/new': typeof LearnerAppWorkspacesNewRoute
  '/app/notebooks/': typeof LearnerAppNotebooksIndexRoute
  '/app/templates/': typeof LearnerAppTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/access-code': typeof LearnerAppAccessCodeRoute
  '/app/consent': typeof LearnerAppConsentRoute
  '/app/credits': typeof LearnerAppCreditsRoute
  '/app/support': typeof LearnerAppSupportRoute
  '/notebooks/$notebookId': typeof LearnerNotebooksNotebookIdRoute
  '/app': typeof LearnerAppIndexRoute
  '/app/account/$tab': typeof LearnerAppAccountTabRoute
  '/app/templates/$templateId': typeof LearnerAppTemplatesTemplateIdRoute
  '/app/workspaces/new': typeof LearnerAppWorkspacesNewRoute
  '/app/notebooks': typeof LearnerAppNotebooksIndexRoute
  '/app/templates': typeof LearnerAppTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_learner': typeof LearnerRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_learner/app/access-code': typeof LearnerAppAccessCodeRoute
  '/_learner/app/consent': typeof LearnerAppConsentRoute
  '/_learner/app/credits': typeof LearnerAppCreditsRoute
  '/_learner/app/support': typeof LearnerAppSupportRoute
  '/_learner/notebooks/$notebookId': typeof LearnerNotebooksNotebookIdRoute
  '/_learner/app/': typeof LearnerAppIndexRoute
  '/_learner/app/account/$tab': typeof LearnerAppAccountTabRoute
  '/_learner/app/templates/$templateId': typeof LearnerAppTemplatesTemplateIdRoute
  '/_learner/app/workspaces/new': typeof LearnerAppWorkspacesNewRoute
  '/_learner/app/notebooks/': typeof LearnerAppNotebooksIndexRoute
  '/_learner/app/templates/': typeof LearnerAppTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/access-code'
    | '/app/consent'
    | '/app/credits'
    | '/app/support'
    | '/notebooks/$notebookId'
    | '/app/'
    | '/app/account/$tab'
    | '/app/templates/$templateId'
    | '/app/workspaces/new'
    | '/app/notebooks/'
    | '/app/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/app/access-code'
    | '/app/consent'
    | '/app/credits'
    | '/app/support'
    | '/notebooks/$notebookId'
    | '/app'
    | '/app/account/$tab'
    | '/app/templates/$templateId'
    | '/app/workspaces/new'
    | '/app/notebooks'
    | '/app/templates'
  id:
    | '__root__'
    | '/'
    | '/_learner'
    | '/contact'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_learner/app/access-code'
    | '/_learner/app/consent'
    | '/_learner/app/credits'
    | '/_learner/app/support'
    | '/_learner/notebooks/$notebookId'
    | '/_learner/app/'
    | '/_learner/app/account/$tab'
    | '/_learner/app/templates/$templateId'
    | '/_learner/app/workspaces/new'
    | '/_learner/app/notebooks/'
    | '/_learner/app/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnerRoute: typeof LearnerRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_learner': {
      id: '/_learner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_learner/app/': {
      id: '/_learner/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof LearnerAppIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/notebooks/$notebookId': {
      id: '/_learner/notebooks/$notebookId'
      path: '/notebooks/$notebookId'
      fullPath: '/notebooks/$notebookId'
      preLoaderRoute: typeof LearnerNotebooksNotebookIdRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/support': {
      id: '/_learner/app/support'
      path: '/app/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof LearnerAppSupportRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/credits': {
      id: '/_learner/app/credits'
      path: '/app/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof LearnerAppCreditsRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/consent': {
      id: '/_learner/app/consent'
      path: '/app/consent'
      fullPath: '/app/consent'
      preLoaderRoute: typeof LearnerAppConsentRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/access-code': {
      id: '/_learner/app/access-code'
      path: '/app/access-code'
      fullPath: '/app/access-code'
      preLoaderRoute: typeof LearnerAppAccessCodeRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/templates/': {
      id: '/_learner/app/templates/'
      path: '/app/templates'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof LearnerAppTemplatesIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/notebooks/': {
      id: '/_learner/app/notebooks/'
      path: '/app/notebooks'
      fullPath: '/app/notebooks/'
      preLoaderRoute: typeof LearnerAppNotebooksIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/workspaces/new': {
      id: '/_learner/app/workspaces/new'
      path: '/app/workspaces/new'
      fullPath: '/app/workspaces/new'
      preLoaderRoute: typeof LearnerAppWorkspacesNewRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/templates/$templateId': {
      id: '/_learner/app/templates/$templateId'
      path: '/app/templates/$templateId'
      fullPath: '/app/templates/$templateId'
      preLoaderRoute: typeof LearnerAppTemplatesTemplateIdRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/account/$tab': {
      id: '/_learner/app/account/$tab'
      path: '/app/account/$tab'
      fullPath: '/app/account/$tab'
      preLoaderRoute: typeof LearnerAppAccountTabRouteImport
      parentRoute: typeof LearnerRoute
    }
  }
}

interface LearnerRouteChildren {
  LearnerAppAccessCodeRoute: typeof LearnerAppAccessCodeRoute
  LearnerAppConsentRoute: typeof LearnerAppConsentRoute
  LearnerAppCreditsRoute: typeof LearnerAppCreditsRoute
  LearnerAppSupportRoute: typeof LearnerAppSupportRoute
  LearnerNotebooksNotebookIdRoute: typeof LearnerNotebooksNotebookIdRoute
  LearnerAppIndexRoute: typeof LearnerAppIndexRoute
  LearnerAppAccountTabRoute: typeof LearnerAppAccountTabRoute
  LearnerAppTemplatesTemplateIdRoute: typeof LearnerAppTemplatesTemplateIdRoute
  LearnerAppWorkspacesNewRoute: typeof LearnerAppWorkspacesNewRoute
  LearnerAppNotebooksIndexRoute: typeof LearnerAppNotebooksIndexRoute
  LearnerAppTemplatesIndexRoute: typeof LearnerAppTemplatesIndexRoute
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerAppAccessCodeRoute: LearnerAppAccessCodeRoute,
  LearnerAppConsentRoute: LearnerAppConsentRoute,
  LearnerAppCreditsRoute: LearnerAppCreditsRoute,
  LearnerAppSupportRoute: LearnerAppSupportRoute,
  LearnerNotebooksNotebookIdRoute: LearnerNotebooksNotebookIdRoute,
  LearnerAppIndexRoute: LearnerAppIndexRoute,
  LearnerAppAccountTabRoute: LearnerAppAccountTabRoute,
  LearnerAppTemplatesTemplateIdRoute: LearnerAppTemplatesTemplateIdRoute,
  LearnerAppWorkspacesNewRoute: LearnerAppWorkspacesNewRoute,
  LearnerAppNotebooksIndexRoute: LearnerAppNotebooksIndexRoute,
  LearnerAppTemplatesIndexRoute: LearnerAppTemplatesIndexRoute,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnerRoute: LearnerRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
