/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LearnerRouteImport } from './routes/_learner'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvalRunsIndexRouteImport } from './routes/eval-runs/index'
import { Route as NotebooksNotebookIdRouteImport } from './routes/notebooks/$notebookId'
import { Route as EvalRunsRunIdRouteImport } from './routes/eval-runs/$runId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LearnerNotebooksIndexRouteImport } from './routes/_learner/notebooks/index'
import { Route as LearnerAppIndexRouteImport } from './routes/_learner/app/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as LearnerAppSupportRouteImport } from './routes/_learner/app/support'
import { Route as LearnerAppCreditsRouteImport } from './routes/_learner/app/credits'
import { Route as LearnerAppConsentRouteImport } from './routes/_learner/app/consent'
import { Route as LearnerAppAccountRouteImport } from './routes/_learner/app/account'
import { Route as LearnerAppAccessCodeRouteImport } from './routes/_learner/app/access-code'
import { Route as AdminAdminWorkspacesRouteImport } from './routes/_admin/admin/workspaces'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminTemplatesRouteImport } from './routes/_admin/admin/templates'
import { Route as AdminAdminIngestionRouteImport } from './routes/_admin/admin/ingestion'
import { Route as AdminAdminFeedbackRouteImport } from './routes/_admin/admin/feedback'
import { Route as AdminAdminCreditsRouteImport } from './routes/_admin/admin/credits'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin/analytics'
import { Route as AdminAdminAccountDeletionRouteImport } from './routes/_admin/admin/account-deletion'
import { Route as AdminAdminAccessCodesRouteImport } from './routes/_admin/admin/access-codes'
import { Route as LearnerAppWorkspacesNewRouteImport } from './routes/_learner/app/workspaces/new'
import { Route as LearnerAppTemplatesTemplateIdRouteImport } from './routes/_learner/app/templates/$templateId'
import { Route as AdminAdminWorkspacesWorkspaceIdRouteImport } from './routes/_admin/admin/workspaces/$workspaceId'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin/users/$userId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoute = LearnerRouteImport.update({
  id: '/_learner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRunsIndexRoute = EvalRunsIndexRouteImport.update({
  id: '/eval-runs/',
  path: '/eval-runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksNotebookIdRoute = NotebooksNotebookIdRouteImport.update({
  id: '/notebooks/$notebookId',
  path: '/notebooks/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRunsRunIdRoute = EvalRunsRunIdRouteImport.update({
  id: '/eval-runs/$runId',
  path: '/eval-runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerNotebooksIndexRoute = LearnerNotebooksIndexRouteImport.update({
  id: '/notebooks/',
  path: '/notebooks/',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppIndexRoute = LearnerAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => LearnerRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const LearnerAppSupportRoute = LearnerAppSupportRouteImport.update({
  id: '/app/support',
  path: '/app/support',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppCreditsRoute = LearnerAppCreditsRouteImport.update({
  id: '/app/credits',
  path: '/app/credits',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppConsentRoute = LearnerAppConsentRouteImport.update({
  id: '/app/consent',
  path: '/app/consent',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppAccountRoute = LearnerAppAccountRouteImport.update({
  id: '/app/account',
  path: '/app/account',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppAccessCodeRoute = LearnerAppAccessCodeRouteImport.update({
  id: '/app/access-code',
  path: '/app/access-code',
  getParentRoute: () => LearnerRoute,
} as any)
const AdminAdminWorkspacesRoute = AdminAdminWorkspacesRouteImport.update({
  id: '/admin/workspaces',
  path: '/admin/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTemplatesRoute = AdminAdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIngestionRoute = AdminAdminIngestionRouteImport.update({
  id: '/admin/ingestion',
  path: '/admin/ingestion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFeedbackRoute = AdminAdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCreditsRoute = AdminAdminCreditsRouteImport.update({
  id: '/admin/credits',
  path: '/admin/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAccountDeletionRoute =
  AdminAdminAccountDeletionRouteImport.update({
    id: '/admin/account-deletion',
    path: '/admin/account-deletion',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAccessCodesRoute = AdminAdminAccessCodesRouteImport.update({
  id: '/admin/access-codes',
  path: '/admin/access-codes',
  getParentRoute: () => AdminRoute,
} as any)
const LearnerAppWorkspacesNewRoute = LearnerAppWorkspacesNewRouteImport.update({
  id: '/app/workspaces/new',
  path: '/app/workspaces/new',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerAppTemplatesTemplateIdRoute =
  LearnerAppTemplatesTemplateIdRouteImport.update({
    id: '/app/templates/$templateId',
    path: '/app/templates/$templateId',
    getParentRoute: () => LearnerRoute,
  } as any)
const AdminAdminWorkspacesWorkspaceIdRoute =
  AdminAdminWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => AdminAdminWorkspacesRoute,
  } as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/eval-runs/$runId': typeof EvalRunsRunIdRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/eval-runs/': typeof EvalRunsIndexRoute
  '/admin/access-codes': typeof AdminAdminAccessCodesRoute
  '/admin/account-deletion': typeof AdminAdminAccountDeletionRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/credits': typeof AdminAdminCreditsRoute
  '/admin/feedback': typeof AdminAdminFeedbackRoute
  '/admin/ingestion': typeof AdminAdminIngestionRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/admin/workspaces': typeof AdminAdminWorkspacesRouteWithChildren
  '/app/access-code': typeof LearnerAppAccessCodeRoute
  '/app/account': typeof LearnerAppAccountRoute
  '/app/consent': typeof LearnerAppConsentRoute
  '/app/credits': typeof LearnerAppCreditsRoute
  '/app/support': typeof LearnerAppSupportRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/app/': typeof LearnerAppIndexRoute
  '/notebooks/': typeof LearnerNotebooksIndexRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/workspaces/$workspaceId': typeof AdminAdminWorkspacesWorkspaceIdRoute
  '/app/templates/$templateId': typeof LearnerAppTemplatesTemplateIdRoute
  '/app/workspaces/new': typeof LearnerAppWorkspacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/eval-runs/$runId': typeof EvalRunsRunIdRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/eval-runs': typeof EvalRunsIndexRoute
  '/admin/access-codes': typeof AdminAdminAccessCodesRoute
  '/admin/account-deletion': typeof AdminAdminAccountDeletionRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/credits': typeof AdminAdminCreditsRoute
  '/admin/feedback': typeof AdminAdminFeedbackRoute
  '/admin/ingestion': typeof AdminAdminIngestionRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/admin/workspaces': typeof AdminAdminWorkspacesRouteWithChildren
  '/app/access-code': typeof LearnerAppAccessCodeRoute
  '/app/account': typeof LearnerAppAccountRoute
  '/app/consent': typeof LearnerAppConsentRoute
  '/app/credits': typeof LearnerAppCreditsRoute
  '/app/support': typeof LearnerAppSupportRoute
  '/admin': typeof AdminAdminIndexRoute
  '/app': typeof LearnerAppIndexRoute
  '/notebooks': typeof LearnerNotebooksIndexRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/workspaces/$workspaceId': typeof AdminAdminWorkspacesWorkspaceIdRoute
  '/app/templates/$templateId': typeof LearnerAppTemplatesTemplateIdRoute
  '/app/workspaces/new': typeof LearnerAppWorkspacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_learner': typeof LearnerRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/eval-runs/$runId': typeof EvalRunsRunIdRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/eval-runs/': typeof EvalRunsIndexRoute
  '/_admin/admin/access-codes': typeof AdminAdminAccessCodesRoute
  '/_admin/admin/account-deletion': typeof AdminAdminAccountDeletionRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/credits': typeof AdminAdminCreditsRoute
  '/_admin/admin/feedback': typeof AdminAdminFeedbackRoute
  '/_admin/admin/ingestion': typeof AdminAdminIngestionRoute
  '/_admin/admin/templates': typeof AdminAdminTemplatesRoute
  '/_admin/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/_admin/admin/workspaces': typeof AdminAdminWorkspacesRouteWithChildren
  '/_learner/app/access-code': typeof LearnerAppAccessCodeRoute
  '/_learner/app/account': typeof LearnerAppAccountRoute
  '/_learner/app/consent': typeof LearnerAppConsentRoute
  '/_learner/app/credits': typeof LearnerAppCreditsRoute
  '/_learner/app/support': typeof LearnerAppSupportRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_learner/app/': typeof LearnerAppIndexRoute
  '/_learner/notebooks/': typeof LearnerNotebooksIndexRoute
  '/_admin/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/_admin/admin/workspaces/$workspaceId': typeof AdminAdminWorkspacesWorkspaceIdRoute
  '/_learner/app/templates/$templateId': typeof LearnerAppTemplatesTemplateIdRoute
  '/_learner/app/workspaces/new': typeof LearnerAppWorkspacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/eval-runs/$runId'
    | '/notebooks/$notebookId'
    | '/eval-runs/'
    | '/admin/access-codes'
    | '/admin/account-deletion'
    | '/admin/analytics'
    | '/admin/credits'
    | '/admin/feedback'
    | '/admin/ingestion'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/workspaces'
    | '/app/access-code'
    | '/app/account'
    | '/app/consent'
    | '/app/credits'
    | '/app/support'
    | '/admin/'
    | '/app/'
    | '/notebooks/'
    | '/admin/users/$userId'
    | '/admin/workspaces/$workspaceId'
    | '/app/templates/$templateId'
    | '/app/workspaces/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/eval-runs/$runId'
    | '/notebooks/$notebookId'
    | '/eval-runs'
    | '/admin/access-codes'
    | '/admin/account-deletion'
    | '/admin/analytics'
    | '/admin/credits'
    | '/admin/feedback'
    | '/admin/ingestion'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/workspaces'
    | '/app/access-code'
    | '/app/account'
    | '/app/consent'
    | '/app/credits'
    | '/app/support'
    | '/admin'
    | '/app'
    | '/notebooks'
    | '/admin/users/$userId'
    | '/admin/workspaces/$workspaceId'
    | '/app/templates/$templateId'
    | '/app/workspaces/new'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_learner'
    | '/contact'
    | '/demo'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/eval-runs/$runId'
    | '/notebooks/$notebookId'
    | '/eval-runs/'
    | '/_admin/admin/access-codes'
    | '/_admin/admin/account-deletion'
    | '/_admin/admin/analytics'
    | '/_admin/admin/credits'
    | '/_admin/admin/feedback'
    | '/_admin/admin/ingestion'
    | '/_admin/admin/templates'
    | '/_admin/admin/users'
    | '/_admin/admin/workspaces'
    | '/_learner/app/access-code'
    | '/_learner/app/account'
    | '/_learner/app/consent'
    | '/_learner/app/credits'
    | '/_learner/app/support'
    | '/_admin/admin/'
    | '/_learner/app/'
    | '/_learner/notebooks/'
    | '/_admin/admin/users/$userId'
    | '/_admin/admin/workspaces/$workspaceId'
    | '/_learner/app/templates/$templateId'
    | '/_learner/app/workspaces/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LearnerRoute: typeof LearnerRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EvalRunsRunIdRoute: typeof EvalRunsRunIdRoute
  NotebooksNotebookIdRoute: typeof NotebooksNotebookIdRoute
  EvalRunsIndexRoute: typeof EvalRunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_learner': {
      id: '/_learner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval-runs/': {
      id: '/eval-runs/'
      path: '/eval-runs'
      fullPath: '/eval-runs/'
      preLoaderRoute: typeof EvalRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$notebookId': {
      id: '/notebooks/$notebookId'
      path: '/notebooks/$notebookId'
      fullPath: '/notebooks/$notebookId'
      preLoaderRoute: typeof NotebooksNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval-runs/$runId': {
      id: '/eval-runs/$runId'
      path: '/eval-runs/$runId'
      fullPath: '/eval-runs/$runId'
      preLoaderRoute: typeof EvalRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_learner/notebooks/': {
      id: '/_learner/notebooks/'
      path: '/notebooks'
      fullPath: '/notebooks/'
      preLoaderRoute: typeof LearnerNotebooksIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/': {
      id: '/_learner/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof LearnerAppIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_learner/app/support': {
      id: '/_learner/app/support'
      path: '/app/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof LearnerAppSupportRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/credits': {
      id: '/_learner/app/credits'
      path: '/app/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof LearnerAppCreditsRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/consent': {
      id: '/_learner/app/consent'
      path: '/app/consent'
      fullPath: '/app/consent'
      preLoaderRoute: typeof LearnerAppConsentRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/account': {
      id: '/_learner/app/account'
      path: '/app/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof LearnerAppAccountRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/access-code': {
      id: '/_learner/app/access-code'
      path: '/app/access-code'
      fullPath: '/app/access-code'
      preLoaderRoute: typeof LearnerAppAccessCodeRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_admin/admin/workspaces': {
      id: '/_admin/admin/workspaces'
      path: '/admin/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminAdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/templates': {
      id: '/_admin/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminAdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/ingestion': {
      id: '/_admin/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminAdminIngestionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/feedback': {
      id: '/_admin/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminAdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/credits': {
      id: '/_admin/admin/credits'
      path: '/admin/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminAdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/account-deletion': {
      id: '/_admin/admin/account-deletion'
      path: '/admin/account-deletion'
      fullPath: '/admin/account-deletion'
      preLoaderRoute: typeof AdminAdminAccountDeletionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/access-codes': {
      id: '/_admin/admin/access-codes'
      path: '/admin/access-codes'
      fullPath: '/admin/access-codes'
      preLoaderRoute: typeof AdminAdminAccessCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_learner/app/workspaces/new': {
      id: '/_learner/app/workspaces/new'
      path: '/app/workspaces/new'
      fullPath: '/app/workspaces/new'
      preLoaderRoute: typeof LearnerAppWorkspacesNewRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/app/templates/$templateId': {
      id: '/_learner/app/templates/$templateId'
      path: '/app/templates/$templateId'
      fullPath: '/app/templates/$templateId'
      preLoaderRoute: typeof LearnerAppTemplatesTemplateIdRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_admin/admin/workspaces/$workspaceId': {
      id: '/_admin/admin/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/admin/workspaces/$workspaceId'
      preLoaderRoute: typeof AdminAdminWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AdminAdminWorkspacesRoute
    }
    '/_admin/admin/users/$userId': {
      id: '/_admin/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminAdminUsersRoute
    }
  }
}

interface AdminAdminUsersRouteChildren {
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
}

const AdminAdminUsersRouteChildren: AdminAdminUsersRouteChildren = {
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
}

const AdminAdminUsersRouteWithChildren = AdminAdminUsersRoute._addFileChildren(
  AdminAdminUsersRouteChildren,
)

interface AdminAdminWorkspacesRouteChildren {
  AdminAdminWorkspacesWorkspaceIdRoute: typeof AdminAdminWorkspacesWorkspaceIdRoute
}

const AdminAdminWorkspacesRouteChildren: AdminAdminWorkspacesRouteChildren = {
  AdminAdminWorkspacesWorkspaceIdRoute: AdminAdminWorkspacesWorkspaceIdRoute,
}

const AdminAdminWorkspacesRouteWithChildren =
  AdminAdminWorkspacesRoute._addFileChildren(AdminAdminWorkspacesRouteChildren)

interface AdminRouteChildren {
  AdminAdminAccessCodesRoute: typeof AdminAdminAccessCodesRoute
  AdminAdminAccountDeletionRoute: typeof AdminAdminAccountDeletionRoute
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminCreditsRoute: typeof AdminAdminCreditsRoute
  AdminAdminFeedbackRoute: typeof AdminAdminFeedbackRoute
  AdminAdminIngestionRoute: typeof AdminAdminIngestionRoute
  AdminAdminTemplatesRoute: typeof AdminAdminTemplatesRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRouteWithChildren
  AdminAdminWorkspacesRoute: typeof AdminAdminWorkspacesRouteWithChildren
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAccessCodesRoute: AdminAdminAccessCodesRoute,
  AdminAdminAccountDeletionRoute: AdminAdminAccountDeletionRoute,
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminCreditsRoute: AdminAdminCreditsRoute,
  AdminAdminFeedbackRoute: AdminAdminFeedbackRoute,
  AdminAdminIngestionRoute: AdminAdminIngestionRoute,
  AdminAdminTemplatesRoute: AdminAdminTemplatesRoute,
  AdminAdminUsersRoute: AdminAdminUsersRouteWithChildren,
  AdminAdminWorkspacesRoute: AdminAdminWorkspacesRouteWithChildren,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LearnerRouteChildren {
  LearnerAppAccessCodeRoute: typeof LearnerAppAccessCodeRoute
  LearnerAppAccountRoute: typeof LearnerAppAccountRoute
  LearnerAppConsentRoute: typeof LearnerAppConsentRoute
  LearnerAppCreditsRoute: typeof LearnerAppCreditsRoute
  LearnerAppSupportRoute: typeof LearnerAppSupportRoute
  LearnerAppIndexRoute: typeof LearnerAppIndexRoute
  LearnerNotebooksIndexRoute: typeof LearnerNotebooksIndexRoute
  LearnerAppTemplatesTemplateIdRoute: typeof LearnerAppTemplatesTemplateIdRoute
  LearnerAppWorkspacesNewRoute: typeof LearnerAppWorkspacesNewRoute
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerAppAccessCodeRoute: LearnerAppAccessCodeRoute,
  LearnerAppAccountRoute: LearnerAppAccountRoute,
  LearnerAppConsentRoute: LearnerAppConsentRoute,
  LearnerAppCreditsRoute: LearnerAppCreditsRoute,
  LearnerAppSupportRoute: LearnerAppSupportRoute,
  LearnerAppIndexRoute: LearnerAppIndexRoute,
  LearnerNotebooksIndexRoute: LearnerNotebooksIndexRoute,
  LearnerAppTemplatesTemplateIdRoute: LearnerAppTemplatesTemplateIdRoute,
  LearnerAppWorkspacesNewRoute: LearnerAppWorkspacesNewRoute,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LearnerRoute: LearnerRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EvalRunsRunIdRoute: EvalRunsRunIdRoute,
  NotebooksNotebookIdRoute: NotebooksNotebookIdRoute,
  EvalRunsIndexRoute: EvalRunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
